#!/usr/bin/env bash

# The below is the commands to use when installing nginx on ubuntu.
# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'


sudo echo 'Hello World!' > /var/www/html/index.html

sudo systemctl start nginx


